### ISSUE TITLE
Debian networking/interfaces file needs to source interfaces.d

### ISSUE THREAD

**Issue by ts-kris** [embeddedTS/distro-seed#52]
Current documentation for recent Debian releases, including those generated by distro-seed, talk about configuring wifi with `/etc/networking/interfaces.d/<interface name>`. However, the shipped interfaces file does not properly source the `interfaces.d/` folder, e.g. it needs the line:
`source /etc/network/interfaces.d/*`

This should be fixed in distro-seed as Debian documentation indicates that

- By default, on a freshly installed Debian system, the interfaces file includes a line to source files in the /etc/network/interfaces.d directory. https://manpages.debian.org/bookworm/ifupdown/interfaces.5.en.html

Either we're not prepping the file correctly, or we're incorrectly modifying it.

**Comment by lionel** [comment]
Good catch. I was wondering about that too.

**Comment by ts-kris** [comment]
It appears `ifupdown2` is responsible for the blunder. Using the base `ifupdown` correctly creates the `interfaces` file and sources `interfaces.d/`
